steps:
  - label: ":docker: Build & Push to GAR"
    command: | 
      echo "Credentials are located at \$GOOGLE_APPLICATION_CREDENTIALS or \$CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE"
    plugins:
      - gcp-workload-identity-federation#v1.4.0:
          audience: "//iam.googleapis.com/projects/123456789/locations/global/workloadIdentityPools/buildkite-example-pipeline/providers/buildkite"
          service-account: "buildkite-example-pipeline@oidc-project.iam.gserviceaccount.com"
      - docker#v5.12.0:
          image: "${GKE_ZONE}-docker.pkg.dev/${PROJECT_ID}/${GCR_REPO_NAME}/${APP_NAME}:${BUILDKITE_COMMIT}"
          always-pull: true
          tags:
            - "${BUILDKITE_COMMIT}"
            - "latest"
          registry: "${GKE_ZONE}-docker.pkg.dev"
          login: true
          # expand-volume-vars: true
          # propagate-environment: true
          # workdir: "/app"
          # shell: ["/bin/sh", "-c"]
          # command: ["docker build -t $IMAGE_TAG . && docker push $IMAGE_TAG"]
    agents:
      queue: "default"
  - label: ":kubernetes: Deploy to GKE"
    command: ".buildkite/deploy.sh"
    agents:
      queue: "default"
